version: '3'

networks:
  swoft-docker-network:
    driver: ${NETWORKS_DRIVER}

volumes:
  swoft:
    driver: ${VOLUMES_DRIVER}
  mysql:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}


services:

### SWOFT Server ##############################################
    swoft:
      container_name: swoft-docker-swoft
      build:
        context: ./swoft
#        dockerfile: Dockerfile
#        dockerfile: Dockerfile-cn
        dockerfile: alpine.Dockerfile-cn
        args:
          - PHP_VERSION=${PHP_VERSION}
          - PHPREDIS_VERSION=${SWOFT_PHPREDIS_VERSION}
          - HIREDIS_VERSION=${SWOFT_HIREDIS_VERSION}
          - SWOOLE_VERSION=${SWOFT_SWOOLE_VERSION}
          - PORT=${NGINX_UPSTREAM_PORT}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      depends_on:
        - redis
        - mysql
      privileged: true
      command:
        - sh
        - -c
        - |
          composer install --no-dev
          composer dump-autoload
          composer clearcache
          php /var/www/swoft/bin/swoft start
      networks:
        - swoft-docker-network

### NGINX Server #########################################
    nginx:
      container_name: swoft-docker-nginx
      build:
        context: ./nginx
        args:
          - NGINX_VERSION=${NGINX_VERSION}
          - UPSTREAM_CONTAINER=${NGINX_UPSTREAM_CONTAINER}
          - UPSTREAM_PORT=${NGINX_UPSTREAM_PORT}
          - CHANGE_SOURCE=${CHANGE_SOURCE}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - swoft
      networks:
        - swoft-docker-network

### MySQL ################################################
    mysql:
      container_name: swoft-docker-mysql
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${MYSQL_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - swoft-docker-network

### Redis ################################################
    redis:
      container_name: swoft-docker-redis
      build:
        context: ./redis
        args:
          - REDIS_VERSION=${REDIS_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - swoft-docker-network